vcm/src/main/java/uk/gov/cshr/vcm/controller/VacancyController.java
vcm/src/main/java/uk/gov/cshr/vcm/repository/VacancyRepository.java

This is a step change to the next story on searching by department which will involve some refactoring.

CSHRCP-302 - Decouples location from keyword search.

---

docker-compose.stack.yml
vcm/src/main/java/uk/gov/cshr/vcm/service/LocationService.java
vcm/src/main/resources/application.yaml

These need checking.  Let's make sure everyone (esp JamesK) is sure these properties are correct before merging to develop.

Docker properties and Location URL

---

docker-compose.stack.yml
vcm/src/main/java/uk/gov/cshr/vcm/service/LocationService.java
vcm/src/main/resources/application.yaml

Reverts Civil-Service-Human-Resources/cshr-api#30

Revert "Docker properties and Location URL"

---

vcm/src/main/resources/application.yaml

Putting this back to db instead of localhost.

Set the db url to jdbc:postgresql://db:5432/cshr from localhost

---

vcm/src/main/java/uk/gov/cshr/vcm/model/SearchParameters.java
vcm/src/main/java/uk/gov/cshr/vcm/model/VacancySearchParameters.java
vcm/src/main/java/uk/gov/cshr/vcm/repository/SearchQueryBuilder.java
vcm/src/main/java/uk/gov/cshr/vcm/repository/VacancyRepository.java
vcm/src/main/java/uk/gov/cshr/vcm/repository/VacancyRepositoryImpl.java
vcm/src/test/java/uk/gov/cshr/vcm/controller/SalaryRangeTest.java
vcm/src/test/java/uk/gov/cshr/vcm/controller/VacancyPage.java
vcm/src/test/resources/application.yml

The test class is currently set to ignore as I'm not sure what settings are needed.

Cshrcp 8 filter by salary

---

vcm/src/main/java/uk/gov/cshr/vcm/controller/VacancyController.java
vcm/src/main/java/uk/gov/cshr/vcm/repository/VacancyRepository.java
vcm/src/test/java/uk/gov/cshr/vcm/controller/ClosingDateTest.java

Changed error handling until the maintain-vacancy-service is running.

Closing date exception throwing moved to controller.

---

vcm/src/main/java/uk/gov/cshr/vcm/model/Vacancy.java

Reverts Civil-Service-Human-Resources/cshr-api#54

Revert "Add applyURL to Vacancy entity"

---

Dockerfile
vcm/pom.xml
vcm/src/main/resources/application.yaml
vcm/src/main/resources/changelog.xml
vcm/src/test/resources/application.yml

Spring Boot runs the liquibase changelog on startup.

SpringBoot liquibase configuration

---

vcm/src/main/java/uk/gov/cshr/vcm/model/Vacancy.java
vcm/src/main/resources/changelog.xml
vcm/src/test/java/uk/gov/cshr/vcm/controller/VacancyControllerTest.java

Added nationality statement

---

.circleci/config.yml
docker-compose.stack.yml
docker-compose.yml

removal of push to docker hub
removal of ssh copy to "old" environment
addition of jenkins notify to kick of deployment pipeline to dev

Cshrcp 747

---

pom.xml
vcm/src/test/java/uk/gov/cshr/vcm/controller/VacancyControllerTest.java

Removes Spring Data Rest capability.

CSHRCP-704 - Removed ability to return all rows from an Entity.

---

vcm/src/main/java/uk/gov/cshr/vcm/model/Department.java
vcm/src/main/java/uk/gov/cshr/vcm/model/DepartmentStatus.java
vcm/src/main/java/uk/gov/cshr/vcm/model/DisabilityConfidenceLevel.java
vcm/src/main/resources/changelog.xml
vcm/src/test/resources/departments.sql
vcm/src/test/resources/docs/swagger.yaml

Extra fields for Departments

---

vcm/src/main/java/uk/gov/cshr/vcm/VcmApplication.java
vcm/src/main/java/uk/gov/cshr/vcm/controller/exception/VacancyError.java
vcm/src/main/java/uk/gov/cshr/vcm/model/Coordinates.java
vcm/src/main/java/uk/gov/cshr/vcm/model/Location.java
vcm/src/main/java/uk/gov/cshr/vcm/model/Vacancy.java
vcm/src/main/java/uk/gov/cshr/vcm/model/VacancySearchParameters.java
vcm/src/main/java/uk/gov/cshr/vcm/service/HibernateSearchService.java
vcm/src/main/resources/changelog.xml
vcm/src/test/java/uk/gov/cshr/vcm/controller/VacancyControllerTest.java
vcm/src/test/resources/docs/swagger.yaml
vcm/src/test/resources/testchangelog.xml

Added personalSpecificationField to Vacancy
Updated swagger accordingly

Cshrcp 857 personal specification

---

pom.xml
vcm/src/main/java/uk/gov/cshr/vcm/controller/VacancyController.java
vcm/src/main/java/uk/gov/cshr/vcm/security/AuthenticationEntryPoint.java
vcm/src/main/java/uk/gov/cshr/vcm/security/WebSecurityConfig.java
vcm/src/main/resources/application.yaml
vcm/src/test/java/uk/gov/cshr/vcm/controller/VacancyControllerTest.java
vcm/src/test/resources/application.yml

CRUD (department/**", "/vacancy/**) requires CRUD_ROLE       
crud_username: crudusername
crud_password: crudpassword
Search (/vacancy/search/**) requires SEARCH_ROLE
search_username: searchusername
search_password: searchpassword

Added basic auth.

---

Dockerfile

Addition of basic auth credentials as parameters.

Cshrcp 985

---

vcm/src/main/java/uk/gov/cshr/vcm/repository/DepartmentRepository.java

Auto evict on update.
Currently just evicts all but can be changed in future/as required.

Evict cache on updates

---

vcm/src/main/java/uk/gov/cshr/vcm/service/HibernateSearchService.java

Fixed the null pointer.. the code was checking the wrong value previously

Correctly check for coordinates before searching with them

---

vcm/src/main/java/uk/gov/cshr/vcm/controller/VacancySearchController.java
vcm/src/test/java/uk/gov/cshr/vcm/controller/search/VacancySearchTests.java

As opposed to not found, previously.

Deactivated vacancies are going, going, HttpStatus.GONE

---

vcm/src/main/java/uk/gov/cshr/vcm/model/Vacancy.java
vcm/src/test/java/uk/gov/cshr/vcm/controller/search/VacancySearchTests.java

updated when a vacancy is updated

Added the ContaineIn annotation to vacancyLocations so the index is

---

.circleci/config.yml
Dockerfile
vcm/src/main/resources/application.yaml
vcm/src/main/resources/logback.xml

This PR updates the API to use a diffent base image (that we can update when we like), also turned down the logging to INFO default, and changed location of logs directory

Cshrcp 1225

---

vcm/src/main/java/uk/gov/cshr/vcm/controller/VacancySearchController.java
vcm/src/main/java/uk/gov/cshr/vcm/controller/exception/VacancyRestResponseExceptionHandler.java
vcm/src/main/java/uk/gov/cshr/vcm/service/LocationService.java
vcm/src/main/java/uk/gov/cshr/vcm/service/SearchService.java
vcm/src/test/java/uk/gov/cshr/vcm/controller/search/VacancySearchTests.java

Handle invalid location search term
Returns 206 (partial) when location lookup fails.
If no results should be retuned to the user, then I think the UI should do this.
Otherwise, major changes will be needed to all the unit tests.

Handle invalid location search term

---

Dockerfile
entrypoint.sh

Use of filebeat container for API, tested in AWS and logs being pushed.

change api to use filebeat

---

vcm/src/main/java/uk/gov/cshr/vcm/controller/exception/VacancyRestResponseExceptionHandler.java
vcm/src/main/java/uk/gov/cshr/vcm/model/Vacancy.java
vcm/src/main/resources/changelog.xml
vcm/src/test/java/uk/gov/cshr/vcm/controller/VacancyControllerTest.java
vcm/src/test/java/uk/gov/cshr/vcm/repository/VacancyRepositoryTest.java

Added java constraint which is handled and appropriate error sent to client
with 400 code

SQL to delete vacancies with no department

---

vcm/src/main/resources/changelog.xml

transaction from adding the not null dept constraint

Separated the changesets so the sql to remove vacancies is in a separate

---

Dockerfile
entrypoint.sh

removal of some extra lines added in Dockerfile presumably via a merge.  Change to the version of jar that is ran by entrypoint.sh

removal of extra lines in docker file and change to entrypoint.sh

---

vcm/src/main/java/uk/gov/cshr/vcm/controller/NotifyController.java
vcm/src/main/java/uk/gov/cshr/vcm/model/Notification.java
vcm/src/main/java/uk/gov/cshr/vcm/security/WebSecurityConfig.java
vcm/src/main/java/uk/gov/cshr/vcm/service/NotifyService.java
vcm/src/main/resources/application.yaml
vcm/src/test/java/uk/gov/cshr/vcm/controller/NotifyControllerTest.java
vcm/src/test/resources/application.yml

* Endpoint for notify service to be called by CS

Cshr 1482 notify endpoint (#118)

---

entrypoint.sh

addition of notify endpoint credentials to entrypoint file

override notify credentials

---

LICENSE
pom.xml
vcm/pom.xml
vcm/src/docs/swagger/swagger.yaml
vcm/src/main/java/uk/gov/cshr/vcm/controller/DepartmentController.java
vcm/src/main/java/uk/gov/cshr/vcm/controller/VacancyController.java
vcm/src/main/java/uk/gov/cshr/vcm/controller/VacancySearchController.java
vcm/src/main/java/uk/gov/cshr/vcm/model/Vacancy.java
vcm/src/main/java/uk/gov/cshr/vcm/model/VacancyMetadata.java
vcm/src/main/java/uk/gov/cshr/vcm/model/VacancyMetadataResponse.java
vcm/src/main/java/uk/gov/cshr/vcm/service/HibernateSearchConfiguration.java
vcm/src/main/java/uk/gov/cshr/vcm/service/HibernateSearchService.java
vcm/src/main/java/uk/gov/cshr/vcm/service/SearchService.java
vcm/src/main/resources/changelog.xml
vcm/src/main/resources/logback-spring.xml
vcm/src/test/resources/application.yml

CSHRCP-1641 - Set log level for root logger to INFO
CSHRCP-1640 - Added new columns to vacancies and vacancylocations tables.
CSHRCP-1639 - Added new endpoint to Swagger.
CSHRCP-1642 - Added MIT License

CSHRCP-1631 - Implemented new endpoint

---

Dockerfile
entrypoint.sh
pom.xml
vcm/pom.xml
vcm/src/test/resources/localscripts/run.sh

@robertraybarnes - Please changes to Ops files re removing version number from built jar file.

CSHRCP-657 - Implemented parent pom and mods for unversionsed jar in build
